name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-dev-image:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: docker/dev
          push: false
          tags: "outbound/dev:latest"
          cache-from: type=gha
          cache-to: type=gha,mode=max

  cargo-release-build:
    needs: build-dev-image
    runs-on: ubuntu-latest
    container:
      image: outbound/dev:latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --release --verbose

  cargo-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --check --verbose

  # cargo-clippy:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - run: cargo clippy --all-targets --verbose

  # cargo-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - run: cargo test --verbose
